### PR TITLE
switched from cookies to local storage. complete #31

### PR DESCRIPTION
**Pull request by samuraiseoul**

### CODE REVIEW

**Comment by samuraiseoul** [comment]
@Sitzilla

**Comment by Sitzilla** [comment]
👍  to the code just curious why we want to use cookies over local storage?

**Comment by samuraiseoul** [comment]
@Sitzilla we don't, I kind of forgot local storage existed as it's not something a lot of people seem to talk about, and it functions basically in this case as a better site only client side cookie, so it makes more sense to use as it has an easier api, I just forgot about them until the cookies sucked and I was thinking if there's a better way.

**Comment by Sitzilla** [comment]
We could do both? If I recall correctly there are certain situations where one will apply but the other will not.  Thats what we do in Simply Measured.

Although I am fine with localhost over cookies.

**Comment by samuraiseoul** [comment]
It won't apply if they use a super old browser that hasn't implemented it yet.

**Pull request merged**
