### PR TITLE
added google analytics. complete #17

### PR DESCRIPTION
**Pull request by samuraiseoul**
@Sitzilla

### CODE REVIEW

**Comment by samuraiseoul** [comment]
I think this works, apparently it's kind of hard to tell until we deploy it live.

**Comment by Sitzilla** [comment]
oh snap!  Do we log into the google analytics dashboard to track?

**Comment by Sitzilla** [comment]
👍

**Comment by samuraiseoul** [comment]
@Sitzilla we will but it's not really doable local host side.

**Pull request merged**
